// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpcenv.proto

#ifndef PROTOBUF_INCLUDED_rpcenv_2eproto
#define PROTOBUF_INCLUDED_rpcenv_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3007000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3007000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/map.h>  // IWYU pragma: export
#include <google/protobuf/map_entry.h>
#include <google/protobuf/map_field_inl.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_rpcenv_2eproto

// Internal implementation detail -- do not use these members.
struct TableStruct_rpcenv_2eproto {
  static const ::google::protobuf::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::ParseTable schema[5]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors_rpcenv_2eproto();
namespace rpcenv {
class Action;
class ActionDefaultTypeInternal;
extern ActionDefaultTypeInternal _Action_default_instance_;
class ArrayNest;
class ArrayNestDefaultTypeInternal;
extern ArrayNestDefaultTypeInternal _ArrayNest_default_instance_;
class ArrayNest_MapEntry_DoNotUse;
class ArrayNest_MapEntry_DoNotUseDefaultTypeInternal;
extern ArrayNest_MapEntry_DoNotUseDefaultTypeInternal _ArrayNest_MapEntry_DoNotUse_default_instance_;
class NDArray;
class NDArrayDefaultTypeInternal;
extern NDArrayDefaultTypeInternal _NDArray_default_instance_;
class Step;
class StepDefaultTypeInternal;
extern StepDefaultTypeInternal _Step_default_instance_;
}  // namespace rpcenv
namespace google {
namespace protobuf {
template<> ::rpcenv::Action* Arena::CreateMaybeMessage<::rpcenv::Action>(Arena*);
template<> ::rpcenv::ArrayNest* Arena::CreateMaybeMessage<::rpcenv::ArrayNest>(Arena*);
template<> ::rpcenv::ArrayNest_MapEntry_DoNotUse* Arena::CreateMaybeMessage<::rpcenv::ArrayNest_MapEntry_DoNotUse>(Arena*);
template<> ::rpcenv::NDArray* Arena::CreateMaybeMessage<::rpcenv::NDArray>(Arena*);
template<> ::rpcenv::Step* Arena::CreateMaybeMessage<::rpcenv::Step>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace rpcenv {

// ===================================================================

class Action final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:rpcenv.Action) */ {
 public:
  Action();
  virtual ~Action();

  Action(const Action& from);

  inline Action& operator=(const Action& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Action(Action&& from) noexcept
    : Action() {
    *this = ::std::move(from);
  }

  inline Action& operator=(Action&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const Action& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Action* internal_default_instance() {
    return reinterpret_cast<const Action*>(
               &_Action_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(Action* other);
  friend void swap(Action& a, Action& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Action* New() const final {
    return CreateMaybeMessage<Action>(nullptr);
  }

  Action* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Action>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Action& from);
  void MergeFrom(const Action& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Action* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .rpcenv.ArrayNest nest_action = 2;
  bool has_nest_action() const;
  void clear_nest_action();
  static const int kNestActionFieldNumber = 2;
  const ::rpcenv::ArrayNest& nest_action() const;
  ::rpcenv::ArrayNest* release_nest_action();
  ::rpcenv::ArrayNest* mutable_nest_action();
  void set_allocated_nest_action(::rpcenv::ArrayNest* nest_action);

  // optional int32 action = 1;
  bool has_action() const;
  void clear_action();
  static const int kActionFieldNumber = 1;
  ::google::protobuf::int32 action() const;
  void set_action(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:rpcenv.Action)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::rpcenv::ArrayNest* nest_action_;
  ::google::protobuf::int32 action_;
  friend struct ::TableStruct_rpcenv_2eproto;
};
// -------------------------------------------------------------------

class NDArray final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:rpcenv.NDArray) */ {
 public:
  NDArray();
  virtual ~NDArray();

  NDArray(const NDArray& from);

  inline NDArray& operator=(const NDArray& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  NDArray(NDArray&& from) noexcept
    : NDArray() {
    *this = ::std::move(from);
  }

  inline NDArray& operator=(NDArray&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const NDArray& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const NDArray* internal_default_instance() {
    return reinterpret_cast<const NDArray*>(
               &_NDArray_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(NDArray* other);
  friend void swap(NDArray& a, NDArray& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline NDArray* New() const final {
    return CreateMaybeMessage<NDArray>(nullptr);
  }

  NDArray* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<NDArray>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const NDArray& from);
  void MergeFrom(const NDArray& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(NDArray* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated int64 shape = 2 [packed = true];
  int shape_size() const;
  void clear_shape();
  static const int kShapeFieldNumber = 2;
  ::google::protobuf::int64 shape(int index) const;
  void set_shape(int index, ::google::protobuf::int64 value);
  void add_shape(::google::protobuf::int64 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
      shape() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
      mutable_shape();

  // optional bytes data = 3;
  bool has_data() const;
  void clear_data();
  static const int kDataFieldNumber = 3;
  const ::std::string& data() const;
  void set_data(const ::std::string& value);
  #if LANG_CXX11
  void set_data(::std::string&& value);
  #endif
  void set_data(const char* value);
  void set_data(const void* value, size_t size);
  ::std::string* mutable_data();
  ::std::string* release_data();
  void set_allocated_data(::std::string* data);

  // optional int32 dtype = 1;
  bool has_dtype() const;
  void clear_dtype();
  static const int kDtypeFieldNumber = 1;
  ::google::protobuf::int32 dtype() const;
  void set_dtype(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:rpcenv.NDArray)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int64 > shape_;
  mutable std::atomic<int> _shape_cached_byte_size_;
  ::google::protobuf::internal::ArenaStringPtr data_;
  ::google::protobuf::int32 dtype_;
  friend struct ::TableStruct_rpcenv_2eproto;
};
// -------------------------------------------------------------------

class ArrayNest_MapEntry_DoNotUse : public ::google::protobuf::internal::MapEntry<ArrayNest_MapEntry_DoNotUse, 
    ::std::string, ::rpcenv::ArrayNest,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
    0 > {
public:
#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
static bool _ParseMap(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  typedef ::google::protobuf::internal::MapEntry<ArrayNest_MapEntry_DoNotUse, 
    ::std::string, ::rpcenv::ArrayNest,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
    0 > SuperType;
  ArrayNest_MapEntry_DoNotUse();
  ArrayNest_MapEntry_DoNotUse(::google::protobuf::Arena* arena);
  void MergeFrom(const ArrayNest_MapEntry_DoNotUse& other);
  static const ArrayNest_MapEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const ArrayNest_MapEntry_DoNotUse*>(&_ArrayNest_MapEntry_DoNotUse_default_instance_); }
  void MergeFrom(const ::google::protobuf::Message& other) final;
  ::google::protobuf::Metadata GetMetadata() const;
};

// -------------------------------------------------------------------

class ArrayNest final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:rpcenv.ArrayNest) */ {
 public:
  ArrayNest();
  virtual ~ArrayNest();

  ArrayNest(const ArrayNest& from);

  inline ArrayNest& operator=(const ArrayNest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ArrayNest(ArrayNest&& from) noexcept
    : ArrayNest() {
    *this = ::std::move(from);
  }

  inline ArrayNest& operator=(ArrayNest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const ArrayNest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ArrayNest* internal_default_instance() {
    return reinterpret_cast<const ArrayNest*>(
               &_ArrayNest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  void Swap(ArrayNest* other);
  friend void swap(ArrayNest& a, ArrayNest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ArrayNest* New() const final {
    return CreateMaybeMessage<ArrayNest>(nullptr);
  }

  ArrayNest* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ArrayNest>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ArrayNest& from);
  void MergeFrom(const ArrayNest& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ArrayNest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  // repeated .rpcenv.ArrayNest vector = 2;
  int vector_size() const;
  void clear_vector();
  static const int kVectorFieldNumber = 2;
  ::rpcenv::ArrayNest* mutable_vector(int index);
  ::google::protobuf::RepeatedPtrField< ::rpcenv::ArrayNest >*
      mutable_vector();
  const ::rpcenv::ArrayNest& vector(int index) const;
  ::rpcenv::ArrayNest* add_vector();
  const ::google::protobuf::RepeatedPtrField< ::rpcenv::ArrayNest >&
      vector() const;

  // map<string, .rpcenv.ArrayNest> map = 3;
  int map_size() const;
  void clear_map();
  static const int kMapFieldNumber = 3;
  const ::google::protobuf::Map< ::std::string, ::rpcenv::ArrayNest >&
      map() const;
  ::google::protobuf::Map< ::std::string, ::rpcenv::ArrayNest >*
      mutable_map();

  // optional .rpcenv.NDArray array = 1;
  bool has_array() const;
  void clear_array();
  static const int kArrayFieldNumber = 1;
  const ::rpcenv::NDArray& array() const;
  ::rpcenv::NDArray* release_array();
  ::rpcenv::NDArray* mutable_array();
  void set_allocated_array(::rpcenv::NDArray* array);

  // @@protoc_insertion_point(class_scope:rpcenv.ArrayNest)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::rpcenv::ArrayNest > vector_;
  ::google::protobuf::internal::MapField<
      ArrayNest_MapEntry_DoNotUse,
      ::std::string, ::rpcenv::ArrayNest,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
      0 > map_;
  ::rpcenv::NDArray* array_;
  friend struct ::TableStruct_rpcenv_2eproto;
};
// -------------------------------------------------------------------

class Step final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:rpcenv.Step) */ {
 public:
  Step();
  virtual ~Step();

  Step(const Step& from);

  inline Step& operator=(const Step& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Step(Step&& from) noexcept
    : Step() {
    *this = ::std::move(from);
  }

  inline Step& operator=(Step&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const Step& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Step* internal_default_instance() {
    return reinterpret_cast<const Step*>(
               &_Step_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  void Swap(Step* other);
  friend void swap(Step& a, Step& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Step* New() const final {
    return CreateMaybeMessage<Step>(nullptr);
  }

  Step* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Step>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Step& from);
  void MergeFrom(const Step& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Step* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .rpcenv.ArrayNest observation = 1;
  bool has_observation() const;
  void clear_observation();
  static const int kObservationFieldNumber = 1;
  const ::rpcenv::ArrayNest& observation() const;
  ::rpcenv::ArrayNest* release_observation();
  ::rpcenv::ArrayNest* mutable_observation();
  void set_allocated_observation(::rpcenv::ArrayNest* observation);

  // optional float reward = 2;
  bool has_reward() const;
  void clear_reward();
  static const int kRewardFieldNumber = 2;
  float reward() const;
  void set_reward(float value);

  // optional bool done = 3;
  bool has_done() const;
  void clear_done();
  static const int kDoneFieldNumber = 3;
  bool done() const;
  void set_done(bool value);

  // optional int32 episode_step = 4;
  bool has_episode_step() const;
  void clear_episode_step();
  static const int kEpisodeStepFieldNumber = 4;
  ::google::protobuf::int32 episode_step() const;
  void set_episode_step(::google::protobuf::int32 value);

  // optional float episode_return = 5;
  bool has_episode_return() const;
  void clear_episode_return();
  static const int kEpisodeReturnFieldNumber = 5;
  float episode_return() const;
  void set_episode_return(float value);

  // @@protoc_insertion_point(class_scope:rpcenv.Step)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::rpcenv::ArrayNest* observation_;
  float reward_;
  bool done_;
  ::google::protobuf::int32 episode_step_;
  float episode_return_;
  friend struct ::TableStruct_rpcenv_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Action

// optional int32 action = 1;
inline bool Action::has_action() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Action::clear_action() {
  action_ = 0;
  _has_bits_[0] &= ~0x00000002u;
}
inline ::google::protobuf::int32 Action::action() const {
  // @@protoc_insertion_point(field_get:rpcenv.Action.action)
  return action_;
}
inline void Action::set_action(::google::protobuf::int32 value) {
  _has_bits_[0] |= 0x00000002u;
  action_ = value;
  // @@protoc_insertion_point(field_set:rpcenv.Action.action)
}

// optional .rpcenv.ArrayNest nest_action = 2;
inline bool Action::has_nest_action() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Action::clear_nest_action() {
  if (nest_action_ != nullptr) nest_action_->Clear();
  _has_bits_[0] &= ~0x00000001u;
}
inline const ::rpcenv::ArrayNest& Action::nest_action() const {
  const ::rpcenv::ArrayNest* p = nest_action_;
  // @@protoc_insertion_point(field_get:rpcenv.Action.nest_action)
  return p != nullptr ? *p : *reinterpret_cast<const ::rpcenv::ArrayNest*>(
      &::rpcenv::_ArrayNest_default_instance_);
}
inline ::rpcenv::ArrayNest* Action::release_nest_action() {
  // @@protoc_insertion_point(field_release:rpcenv.Action.nest_action)
  _has_bits_[0] &= ~0x00000001u;
  ::rpcenv::ArrayNest* temp = nest_action_;
  nest_action_ = nullptr;
  return temp;
}
inline ::rpcenv::ArrayNest* Action::mutable_nest_action() {
  _has_bits_[0] |= 0x00000001u;
  if (nest_action_ == nullptr) {
    auto* p = CreateMaybeMessage<::rpcenv::ArrayNest>(GetArenaNoVirtual());
    nest_action_ = p;
  }
  // @@protoc_insertion_point(field_mutable:rpcenv.Action.nest_action)
  return nest_action_;
}
inline void Action::set_allocated_nest_action(::rpcenv::ArrayNest* nest_action) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete nest_action_;
  }
  if (nest_action) {
    ::google::protobuf::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      nest_action = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, nest_action, submessage_arena);
    }
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  nest_action_ = nest_action;
  // @@protoc_insertion_point(field_set_allocated:rpcenv.Action.nest_action)
}

// -------------------------------------------------------------------

// NDArray

// optional int32 dtype = 1;
inline bool NDArray::has_dtype() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void NDArray::clear_dtype() {
  dtype_ = 0;
  _has_bits_[0] &= ~0x00000002u;
}
inline ::google::protobuf::int32 NDArray::dtype() const {
  // @@protoc_insertion_point(field_get:rpcenv.NDArray.dtype)
  return dtype_;
}
inline void NDArray::set_dtype(::google::protobuf::int32 value) {
  _has_bits_[0] |= 0x00000002u;
  dtype_ = value;
  // @@protoc_insertion_point(field_set:rpcenv.NDArray.dtype)
}

// repeated int64 shape = 2 [packed = true];
inline int NDArray::shape_size() const {
  return shape_.size();
}
inline void NDArray::clear_shape() {
  shape_.Clear();
}
inline ::google::protobuf::int64 NDArray::shape(int index) const {
  // @@protoc_insertion_point(field_get:rpcenv.NDArray.shape)
  return shape_.Get(index);
}
inline void NDArray::set_shape(int index, ::google::protobuf::int64 value) {
  shape_.Set(index, value);
  // @@protoc_insertion_point(field_set:rpcenv.NDArray.shape)
}
inline void NDArray::add_shape(::google::protobuf::int64 value) {
  shape_.Add(value);
  // @@protoc_insertion_point(field_add:rpcenv.NDArray.shape)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
NDArray::shape() const {
  // @@protoc_insertion_point(field_list:rpcenv.NDArray.shape)
  return shape_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
NDArray::mutable_shape() {
  // @@protoc_insertion_point(field_mutable_list:rpcenv.NDArray.shape)
  return &shape_;
}

// optional bytes data = 3;
inline bool NDArray::has_data() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void NDArray::clear_data() {
  data_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _has_bits_[0] &= ~0x00000001u;
}
inline const ::std::string& NDArray::data() const {
  // @@protoc_insertion_point(field_get:rpcenv.NDArray.data)
  return data_.GetNoArena();
}
inline void NDArray::set_data(const ::std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:rpcenv.NDArray.data)
}
#if LANG_CXX11
inline void NDArray::set_data(::std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  data_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:rpcenv.NDArray.data)
}
#endif
inline void NDArray::set_data(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:rpcenv.NDArray.data)
}
inline void NDArray::set_data(const void* value, size_t size) {
  _has_bits_[0] |= 0x00000001u;
  data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:rpcenv.NDArray.data)
}
inline ::std::string* NDArray::mutable_data() {
  _has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_mutable:rpcenv.NDArray.data)
  return data_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* NDArray::release_data() {
  // @@protoc_insertion_point(field_release:rpcenv.NDArray.data)
  if (!has_data()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return data_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void NDArray::set_allocated_data(::std::string* data) {
  if (data != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  data_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), data);
  // @@protoc_insertion_point(field_set_allocated:rpcenv.NDArray.data)
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// ArrayNest

// optional .rpcenv.NDArray array = 1;
inline bool ArrayNest::has_array() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ArrayNest::clear_array() {
  if (array_ != nullptr) array_->Clear();
  _has_bits_[0] &= ~0x00000001u;
}
inline const ::rpcenv::NDArray& ArrayNest::array() const {
  const ::rpcenv::NDArray* p = array_;
  // @@protoc_insertion_point(field_get:rpcenv.ArrayNest.array)
  return p != nullptr ? *p : *reinterpret_cast<const ::rpcenv::NDArray*>(
      &::rpcenv::_NDArray_default_instance_);
}
inline ::rpcenv::NDArray* ArrayNest::release_array() {
  // @@protoc_insertion_point(field_release:rpcenv.ArrayNest.array)
  _has_bits_[0] &= ~0x00000001u;
  ::rpcenv::NDArray* temp = array_;
  array_ = nullptr;
  return temp;
}
inline ::rpcenv::NDArray* ArrayNest::mutable_array() {
  _has_bits_[0] |= 0x00000001u;
  if (array_ == nullptr) {
    auto* p = CreateMaybeMessage<::rpcenv::NDArray>(GetArenaNoVirtual());
    array_ = p;
  }
  // @@protoc_insertion_point(field_mutable:rpcenv.ArrayNest.array)
  return array_;
}
inline void ArrayNest::set_allocated_array(::rpcenv::NDArray* array) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete array_;
  }
  if (array) {
    ::google::protobuf::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      array = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, array, submessage_arena);
    }
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  array_ = array;
  // @@protoc_insertion_point(field_set_allocated:rpcenv.ArrayNest.array)
}

// repeated .rpcenv.ArrayNest vector = 2;
inline int ArrayNest::vector_size() const {
  return vector_.size();
}
inline void ArrayNest::clear_vector() {
  vector_.Clear();
}
inline ::rpcenv::ArrayNest* ArrayNest::mutable_vector(int index) {
  // @@protoc_insertion_point(field_mutable:rpcenv.ArrayNest.vector)
  return vector_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::rpcenv::ArrayNest >*
ArrayNest::mutable_vector() {
  // @@protoc_insertion_point(field_mutable_list:rpcenv.ArrayNest.vector)
  return &vector_;
}
inline const ::rpcenv::ArrayNest& ArrayNest::vector(int index) const {
  // @@protoc_insertion_point(field_get:rpcenv.ArrayNest.vector)
  return vector_.Get(index);
}
inline ::rpcenv::ArrayNest* ArrayNest::add_vector() {
  // @@protoc_insertion_point(field_add:rpcenv.ArrayNest.vector)
  return vector_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::rpcenv::ArrayNest >&
ArrayNest::vector() const {
  // @@protoc_insertion_point(field_list:rpcenv.ArrayNest.vector)
  return vector_;
}

// map<string, .rpcenv.ArrayNest> map = 3;
inline int ArrayNest::map_size() const {
  return map_.size();
}
inline void ArrayNest::clear_map() {
  map_.Clear();
}
inline const ::google::protobuf::Map< ::std::string, ::rpcenv::ArrayNest >&
ArrayNest::map() const {
  // @@protoc_insertion_point(field_map:rpcenv.ArrayNest.map)
  return map_.GetMap();
}
inline ::google::protobuf::Map< ::std::string, ::rpcenv::ArrayNest >*
ArrayNest::mutable_map() {
  // @@protoc_insertion_point(field_mutable_map:rpcenv.ArrayNest.map)
  return map_.MutableMap();
}

// -------------------------------------------------------------------

// Step

// optional .rpcenv.ArrayNest observation = 1;
inline bool Step::has_observation() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Step::clear_observation() {
  if (observation_ != nullptr) observation_->Clear();
  _has_bits_[0] &= ~0x00000001u;
}
inline const ::rpcenv::ArrayNest& Step::observation() const {
  const ::rpcenv::ArrayNest* p = observation_;
  // @@protoc_insertion_point(field_get:rpcenv.Step.observation)
  return p != nullptr ? *p : *reinterpret_cast<const ::rpcenv::ArrayNest*>(
      &::rpcenv::_ArrayNest_default_instance_);
}
inline ::rpcenv::ArrayNest* Step::release_observation() {
  // @@protoc_insertion_point(field_release:rpcenv.Step.observation)
  _has_bits_[0] &= ~0x00000001u;
  ::rpcenv::ArrayNest* temp = observation_;
  observation_ = nullptr;
  return temp;
}
inline ::rpcenv::ArrayNest* Step::mutable_observation() {
  _has_bits_[0] |= 0x00000001u;
  if (observation_ == nullptr) {
    auto* p = CreateMaybeMessage<::rpcenv::ArrayNest>(GetArenaNoVirtual());
    observation_ = p;
  }
  // @@protoc_insertion_point(field_mutable:rpcenv.Step.observation)
  return observation_;
}
inline void Step::set_allocated_observation(::rpcenv::ArrayNest* observation) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete observation_;
  }
  if (observation) {
    ::google::protobuf::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      observation = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, observation, submessage_arena);
    }
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  observation_ = observation;
  // @@protoc_insertion_point(field_set_allocated:rpcenv.Step.observation)
}

// optional float reward = 2;
inline bool Step::has_reward() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Step::clear_reward() {
  reward_ = 0;
  _has_bits_[0] &= ~0x00000002u;
}
inline float Step::reward() const {
  // @@protoc_insertion_point(field_get:rpcenv.Step.reward)
  return reward_;
}
inline void Step::set_reward(float value) {
  _has_bits_[0] |= 0x00000002u;
  reward_ = value;
  // @@protoc_insertion_point(field_set:rpcenv.Step.reward)
}

// optional bool done = 3;
inline bool Step::has_done() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Step::clear_done() {
  done_ = false;
  _has_bits_[0] &= ~0x00000004u;
}
inline bool Step::done() const {
  // @@protoc_insertion_point(field_get:rpcenv.Step.done)
  return done_;
}
inline void Step::set_done(bool value) {
  _has_bits_[0] |= 0x00000004u;
  done_ = value;
  // @@protoc_insertion_point(field_set:rpcenv.Step.done)
}

// optional int32 episode_step = 4;
inline bool Step::has_episode_step() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Step::clear_episode_step() {
  episode_step_ = 0;
  _has_bits_[0] &= ~0x00000008u;
}
inline ::google::protobuf::int32 Step::episode_step() const {
  // @@protoc_insertion_point(field_get:rpcenv.Step.episode_step)
  return episode_step_;
}
inline void Step::set_episode_step(::google::protobuf::int32 value) {
  _has_bits_[0] |= 0x00000008u;
  episode_step_ = value;
  // @@protoc_insertion_point(field_set:rpcenv.Step.episode_step)
}

// optional float episode_return = 5;
inline bool Step::has_episode_return() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void Step::clear_episode_return() {
  episode_return_ = 0;
  _has_bits_[0] &= ~0x00000010u;
}
inline float Step::episode_return() const {
  // @@protoc_insertion_point(field_get:rpcenv.Step.episode_return)
  return episode_return_;
}
inline void Step::set_episode_return(float value) {
  _has_bits_[0] |= 0x00000010u;
  episode_return_ = value;
  // @@protoc_insertion_point(field_set:rpcenv.Step.episode_return)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace rpcenv

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // PROTOBUF_INCLUDED_rpcenv_2eproto
